import { useParams } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card';
import { Leaderboard } from '../../components/Leaderboard';
import { ArrowUpRight, BarChart3, CheckCircle2, CircleAlert } from 'lucide-react';

const accuracy = [['Q1', 92], ['Q2', 76], ['Q3', 68], ['Q4', 84], ['Q5', 55], ['Q6', 73], ['Q7', 89], ['Q8', 64]];
export function QuizAnalytics() {
  const { id: quizId } = useParams<{ id: string }>();
  return <div className="space-y-6"><div><p className="text-sm font-medium text-primary">Quiz performance</p><h1 className="text-3xl font-bold tracking-tight">Quiz analytics</h1><p className="mt-1 text-muted-foreground">Detailed breakdown of class performance for this assessment.</p></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><Metric label="Class average" value="82%" note="+6.4% from last quiz" icon={BarChart3} color="text-primary" /><Metric label="Completion rate" value="91%" note="68 of 75 students" icon={CheckCircle2} color="text-emerald-400" /><Metric label="Needs review" value="3" note="high-error questions" icon={CircleAlert} color="text-amber-400" /></div><Card><CardHeader className="border-b border-white/10"><CardTitle className="text-lg">Per-question accuracy</CardTitle></CardHeader><CardContent className="p-6"><div className="flex h-56 items-end gap-3 sm:gap-6">{accuracy.map(([label, value]) => <div key={label} className="flex flex-1 flex-col items-center gap-2"><span className="text-xs font-semibold">{value}%</span><div className="w-full rounded-t-lg bg-primary/80" style={{ height: `${Number(value) * 1.8}px` }} /><span className="text-xs text-muted-foreground">{label}</span></div>)}</div></CardContent></Card><Card><CardHeader className="flex flex-row items-center justify-between border-b border-white/10"><CardTitle className="text-lg">Class insight</CardTitle><ArrowUpRight className="h-4 w-4 text-primary" /></CardHeader><CardContent className="p-6 text-sm text-muted-foreground">Students performed strongest on the accounting equation and ledger entries. Review the depreciation and control-account questions before the next revision session.</CardContent></Card><Leaderboard quizId={quizId || 'q1'} /></div>;
}
function Metric({ label, value, note, icon: Icon, color }: { label: string; value: string; note: string; icon: typeof BarChart3; color: string }) { return <Card><CardContent className="p-5"><div className="mb-4 flex items-center justify-between"><span className="text-sm text-muted-foreground">{label}</span><Icon className={`h-5 w-5 ${color}`} /></div><p className="text-3xl font-bold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></CardContent></Card>; }
